In [1]:
import pandas as pd
import sklearn as sk
import numpy as np

# Notes
    *spam--> Wrong msgb
    *ham --> Right msg

In [2]:
dataset = pd.read_csv("smsspamcollection.tsv", sep="\t")
dataset

label                                            message  length  punct
0      ham  Go until jurong point, crazy.. Available only ...     111      9
1      ham                      Ok lar... Joking wif u oni...      29      6
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3      ham  U dun say so early hor... U c already then say...      49      6
4      ham  Nah I don't think he goes to usf, he lives aro...      61      2
...    ...                                                ...     ...    ...
5567  spam  This is the 2nd time we have tried 2 contact u...     160      8
5568   ham               Will ü b going to esplanade fr home?      36      1
5569   ham  Pity, * was in mood for that. So...any other s...      57      7
5570   ham  The guy did some bitching but I acted like i'd...     125      1
5571   ham                         Rofl. Its true to its name      26      1

[5572 rows x 4 columns]

In [3]:
dataset["label"].unique()

array(['ham', 'spam'], dtype=object)

In [4]:
len(dataset)

5572

In [5]:
dataset.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [6]:
dataset["label"].unique()

array(['ham', 'spam'], dtype=object)

In [7]:
dataset["label"].value_counts(normalize=True)# if we just check on this way the accuracy will be 86% cuz we have class imbalance

ham     0.865937
spam    0.134063
Name: label, dtype: float64

In [8]:
dataset["length"].describe()

count    5572.000000
mean       80.489950
std        59.942907
min         2.000000
25%        36.000000
50%        62.000000
75%       122.000000
max       910.000000
Name: length, dtype: float64

In [9]:
dataset["punct"].describe()

count    5572.000000
mean        4.177495
std         4.623919
min         0.000000
25%         2.000000
50%         3.000000
75%         6.000000
max       133.000000
Name: punct, dtype: float64

In [10]:
x = dataset[["length","punct"]]
y = dataset["label"]
x,y

(      length  punct
 0        111      9
 1         29      6
 2        155      6
 3         49      6
 4         61      2
 ...      ...    ...
 5567     160      8
 5568      36      1
 5569      57      7
 5570     125      1
 5571      26      1
 
 [5572 rows x 2 columns],
 0        ham
 1        ham
 2       spam
 3        ham
 4        ham
         ... 
 5567    spam
 5568     ham
 5569     ham
 5570     ham
 5571     ham
 Name: label, Length: 5572, dtype: object)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state = 55)
print("Training Data", X_train.shape)
print("Training Data", X_test.shape)

Training Data (3733, 2)
Training Data (1839, 2)


In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
X_train.head(),y_train.head()

(      length  punct
 1365     114      6
 5116      53      2
 1501      34      2
 1029      49      3
 4847      54      0,
 1365    ham
 5116    ham
 1501    ham
 1029    ham
 4847    ham
 Name: label, dtype: object)

In [15]:
lr_model = LogisticRegression(solver="lbfgs") # Our Classifier
lr_model.fit(X_train,y_train) # We are training our model over our Data using our classifier(training var, Target var)

LogisticRegression()

In [16]:
from sklearn import metrics

In [17]:
prediction = lr_model.predict(X_test)
print(metrics.confusion_matrix(y_test,prediction))

[[1545   38]
 [ 251    5]]


In [18]:
print(metrics.classification_report(y_test,prediction))# Accuracy went 84% now we will use some other classifier

              precision    recall  f1-score   support

         ham       0.86      0.98      0.91      1583
        spam       0.12      0.02      0.03       256

    accuracy                           0.84      1839
   macro avg       0.49      0.50      0.47      1839
weighted avg       0.76      0.84      0.79      1839



# Using Naive bayes Classifier now

In [19]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
nb_model = MultinomialNB()
nb_model.fit(X_train,y_train)

MultinomialNB()

In [21]:
prediction = nb_model.predict(X_test)
print(metrics.confusion_matrix(y_test,prediction))

[[1577    6]
 [ 252    4]]


In [22]:
print(metrics.classification_report(y_test,prediction))# Accuracy is 86% now but not good try something else now

              precision    recall  f1-score   support

         ham       0.86      1.00      0.92      1583
        spam       0.40      0.02      0.03       256

    accuracy                           0.86      1839
   macro avg       0.63      0.51      0.48      1839
weighted avg       0.80      0.86      0.80      1839



# Using Support Vector Classifer now

In [23]:
from sklearn.svm import SVC

In [24]:
svc_model = SVC(gamma = 'auto')
svc_model.fit(X_train,y_train)


SVC(gamma='auto')

In [25]:
prediction = svc_model.predict(X_test)
print(metrics.confusion_matrix(y_test,prediction))

[[1506   77]
 [ 137  119]]


In [26]:
print(metrics.classification_report(y_test,prediction))# Accuracy is 88% now getting Better finally

              precision    recall  f1-score   support

         ham       0.92      0.95      0.93      1583
        spam       0.61      0.46      0.53       256

    accuracy                           0.88      1839
   macro avg       0.76      0.71      0.73      1839
weighted avg       0.87      0.88      0.88      1839

